export const CAKE_ORDERED = 'CAKE_ORDERED';
export const CAKE_RESTOCKED = 'CAKE_RESTOCKED';

export const ICECREAM_ORDERED = 'ICECREAM_ORDERED';
export const ICECREAM_RESTOCKED = 'ICECREAM_RESTOCKED';
